import { Loader, Sparkles } from "lucide-react";
import { Mood } from "../types/moods";
import { ReflectionData } from "../types/reflection";
import { findMoodByName } from "../utils/moodUtils";
import { MoodEmoji } from "@/components/MoodEmoji";
import styles from "../app/Journal/journal.module.css";

interface ReflectionSectionProps {
  show: boolean;
  reflectionLoading: boolean;
  generatedReflection: ReflectionData | null;
  detectedMoods: string[];
  moods: Mood[];
  isLocked: boolean;
  onRegenerateReflection: () => void;
  onGenerateNewReflection: () => void;
}

/**
 * Displays AI-generated reflection with detected moods
 */
export function ReflectionSection({
  show,
  reflectionLoading,
  generatedReflection,
  detectedMoods,
  moods,
  isLocked,
  onRegenerateReflection,
  onGenerateNewReflection,
}: ReflectionSectionProps) {
  if (!show) return null;

  return (
    <section className={styles.reflection}>
      <div className={styles.reflectionHeader}>
        <div className={styles.sparkle} aria-hidden="true">
          {reflectionLoading ? (
            <Loader size={20} className="animate-spin" />
          ) : (
            <Sparkles size={20} />
          )}
        </div>

        <div>
          <h2>A little reflection</h2>
          <p>Here's what I noticed in your entry.</p>
        </div>
      </div>

      {reflectionLoading && (
        <p
          style={{
            textAlign: "center",
            color: "#999",
            marginTop: "1rem",
          }}
          aria-busy="true"
        >
          Generating reflection... This may take a moment.
        </p>
      )}

      {/* AI-Detected Moods Section */}
      {detectedMoods.length > 0 && !reflectionLoading && (
        <div className={styles.detectedMood}>
          <div className={styles.detectedMoodEmojis}>
            {detectedMoods.map((mood) => {
              const moodObj = findMoodByName(moods, mood);

              return (
                <div key={mood} className={styles.detectedMoodEmoji}>
                  {moodObj?.animatedEmojiUrl ? (
                    <MoodEmoji
                      animatedEmojiUrl={moodObj.animatedEmojiUrl}
                      size={50}
                    />
                  ) : (
                    <span title={`${mood} emoji not found`}>💭</span>
                  )}
                </div>
              );
            })}
          </div>

          <div>
            <p>🤖 AI Detected:</p>
            <strong>{detectedMoods.join(", ")}</strong>
            <p
              style={{
                fontSize: "0.875rem",
                color: "#999",
                marginTop: "0.5rem",
              }}
            >
              (The AI detected these emotions in your entry)
            </p>
          </div>
        </div>
      )}

      {/* Reflection Text */}
      {generatedReflection?.reflection && !reflectionLoading && (
        <div style={{ marginTop: "1.5rem" }}>
          <p className={styles.reflectionText}>
            <strong>📝 Reflection:</strong>
          </p>
          <p className={styles.reflectionText}>
            {generatedReflection.reflection}
          </p>
        </div>
      )}

      {/* Advice Section */}
      {generatedReflection?.advice && !reflectionLoading && (
        <div style={{ marginTop: "1.5rem" }}>
          <p className={styles.reflectionText}>
            <strong>💡 My Advice:</strong>
          </p>
          <p className={styles.reflectionText}>{generatedReflection.advice}</p>
        </div>
      )}

      <p className={styles.aiDisclaimer}>
        ✨ This reflection was generated by AI and is not a diagnosis.
      </p>

      {/* Action Buttons */}
      {!isLocked && (
        <div className={styles.reflectionActions}>
          <button
            onClick={onRegenerateReflection}
            disabled={reflectionLoading}
            aria-busy={reflectionLoading}
          >
            {reflectionLoading ? "Generating..." : "Get another reflection"}
          </button>
        </div>
      )}
    </section>
  );
}
